# 第1个视频：NumPy和Pandas有什么用

> 原视频 P1：1.1 numpy & pandas 有什么用？｜时长：3分26秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

## 1. NumPy是什么

NumPy 的完整名称是：

```text
Numerical Python
```

也就是“用于数值计算的 Python 工具”。

NumPy 最重要的数据类型是：

```python
ndarray
```

平时一般把它叫作：

- NumPy 数组
- array
- 多维数组

它特别适合处理大量数字，例如：

- 学生成绩
- 股票价格
- 图片像素
- 实验数据
- 机器学习数据
- 矩阵运算

---

## 2. Python列表和NumPy数组的区别

先看普通列表：


In [ ]:
a = [1, 2, 3]
b = [10, 20, 30]

print(a + b)


输出：

```text
[1, 2, 3, 10, 20, 30]
```

列表的 `+` 表示拼接，不是对应位置相加。

如果想让列表对应位置相加，需要这样写：


In [ ]:
a = [1, 2, 3]
b = [10, 20, 30]

result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)


输出：

```text
[11, 22, 33]
```

使用 NumPy：


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)


输出：

```text
[11 22 33]
```

NumPy 会自动进行对应位置运算：

```text
1  + 10 = 11
2  + 20 = 22
3  + 30 = 33
```

这叫作：

```text
向量化运算
```

意思是不用自己写循环，直接对整个数组进行计算。

---

## 3. 为什么NumPy通常比列表快

普通 Python 列表可以存放不同类型：


In [ ]:
data = [10, "你好", 3.14, True]


NumPy 数组一般保存相同类型的数据：


In [ ]:
data = np.array([10, 20, 30, 40])


输出：

```text
[10 20 30 40]
```

它的数据类型通常统一，因此：

- 内存排列更紧密
- 底层大量操作使用编译后的代码实现
- 可以一次处理一组数字
- 不需要在 Python 中逐个执行循环

不过要注意：

> NumPy主要在数据量较大、能够使用向量化运算时体现优势。只有几个数字时，速度差别未必重要。

作者在本集主要强调 NumPy、Pandas 常用于数据分析、机器学习和深度学习，并且比直接使用列表处理大量数值更方便。[作者的课程说明](https://mofanpy.com/tutorials/data-manipulation/np-pd/why)

---

## 4. Pandas是什么

Pandas 是更偏向“表格数据处理”的工具。

NumPy 数组：


In [ ]:
import numpy as np

scores = np.array([
    [90, 85],
    [78, 92],
    [88, 76]
])

print(scores)


输出：

```text
[[90 85]
 [78 92]
 [88 76]]
```

这里只能看到数字，不知道每行、每列表示什么。

Pandas 可以加上行名和列名：


In [ ]:
import pandas as pd

scores = pd.DataFrame(
    [
        [90, 85],
        [78, 92],
        [88, 76]
    ],
    index=["小明", "小红", "小刚"],
    columns=["语文", "数学"]
)

print(scores)


输出：

```text
    语文  数学
小明  90  85
小红  78  92
小刚  88  76
```

Pandas 的优势是可以处理：

- 行标签和列标签
- 表格数据
- 缺失数据
- CSV、Excel等文件
- 数据筛选
- 数据合并
- 分组统计
- 时间序列

---

## 5. NumPy和Pandas的关系

可以这样理解：

```text
NumPy：擅长数字、多维数组、数学运算
Pandas：擅长有行列名称的表格数据
```

例如：

```text
图片像素、矩阵计算  → NumPy
Excel表格、学生成绩 → Pandas
```

很多 Pandas 功能也建立在 NumPy 的数组计算能力之上。

---
