# 第3个视频：NumPy属性

> 原视频 P3：2.1 numpy 属性｜时长：6分28秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

本集主要介绍：

```python
ndim
shape
size
```

再补充一个非常常用的：

```python
dtype
```

作者的本集示例和输出可以在[NumPy属性配套内容](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-attributes)中查看。

## 1. 创建二维数组


In [3]:
import numpy as np

array = np.array([
    [1, 2, 3],
    [2, 3, 4]
])

print(array)


[[1 2 3]
 [2 3 4]]


输出：

```text
[[1 2 3]
 [2 3 4]]
```

它的结构是：

```text
第0行：[1, 2, 3]
第1行：[2, 3, 4]
```

一共有：

```text
2行 × 3列
```

原视频经常把它称为“矩阵”，便于初学者理解；更准确地说，`np.array()` 创建的是 `ndarray`。二维 `ndarray` 可以当作矩阵进行很多运算。

---

## 2. `ndim`：维度数量


In [4]:
print(array.ndim)


2


输出：

```text
2
```

因为它需要两个索引才能找到一个元素：

```python
array[行, 列]
```

例如：


In [5]:
print(array[1, 2])


4


输出：

```text
4
```

这里：

```text
行索引 = 1
列索引 = 2
```

对应第二行、第三列。

注意索引从 `0` 开始。

---

### 一维数组


In [6]:
a = np.array([10, 20, 30])

print(a.ndim)


1


输出：

```text
1
```

### 二维数组


In [ ]:
b = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(b.ndim)


输出：

```text
2
```

### 三维数组


In [7]:
c = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(c.ndim)


3


输出：

```text
3
```

可以暂时把三维数组想成“两张二维表叠在一起”。

---

## 3. `shape`：每个维度的长度


In [8]:
array = np.array([
    [1, 2, 3],
    [2, 3, 4]
])

print(array.shape)


(2, 3)


输出：

```text
(2, 3)
```

意思是：

```text
2行，3列
```

`shape` 返回的是元组：

```python
(2, 3)
```

可以分别取出来：


In [9]:
rows = array.shape[0]
columns = array.shape[1]

print("行数：", rows)
print("列数：", columns)


行数： 2
列数： 3


输出：

```text
行数： 2
列数： 3
```

---

### 一维数组的shape


In [ ]:
a = np.array([10, 20, 30])

print(a.shape)


输出：

```text
(3,)
```

为什么不是：

```text
(1, 3)
```

因为这个数组只有一个维度，长度是3。

`(3,)` 里面的逗号表示它是一个只有一个元素的元组。

---

### 二维的一行数组


In [ ]:
a = np.array([[10, 20, 30]])

print(a.ndim)
print(a.shape)


输出：

```text
2
(1, 3)
```

区别：

```python
np.array([10, 20, 30])
```

是：

```text
一维，shape = (3,)
```

而：

```python
np.array([[10, 20, 30]])
```

是：

```text
二维，1行3列，shape = (1, 3)
```

外面多了一层中括号，维度就不同。

---

## 4. `size`：所有元素的总数量


In [ ]:
array = np.array([
    [1, 2, 3],
    [2, 3, 4]
])

print(array.size)


输出：

```text
6
```

计算过程：

```text
2行 × 3列 = 6个元素
```

再看：


In [ ]:
a = np.zeros((3, 4))

print(a.shape)
print(a.size)


输出：

```text
(3, 4)
12
```

因为：

```text
3 × 4 = 12
```

---

## 5. `dtype`：元素的数据类型


In [ ]:
array = np.array([1, 2, 3])

print(array.dtype)


在多数64位环境中通常输出：

```text
int64
```

但也可能因操作系统和环境而不同。

如果数组包含小数：


In [ ]:
array = np.array([1, 2.5, 3])

print(array)
print(array.dtype)


输出：

```text
[1.  2.5 3. ]
float64
```

为什么整数变成了小数？

因为 NumPy 数组通常要求元素使用统一的数据类型。为了保存 `2.5`，NumPy 会把其他整数也转换成浮点数：

```text
1   → 1.0
2.5 → 2.5
3   → 3.0
```

---

## 6. 四个属性总结


In [ ]:
import numpy as np

array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("数组：")
print(array)

print("维度：", array.ndim)
print("形状：", array.shape)
print("元素总数：", array.size)
print("数据类型：", array.dtype)


输出通常为：

```text
数组：
[[1 2 3]
 [4 5 6]]
维度： 2
形状： (2, 3)
元素总数： 6
数据类型： int64
```

可以这样记：

```text
ndim  → 几维
shape → 每一维分别多长
size  → 总共多少个元素
dtype → 元素是什么类型
```

---
