# 第4个视频：创建NumPy数组

> 原视频 P4：2.2 numpy 的创建 array｜时长：11分54秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

本集重点是：

- `np.array()`
- `dtype`
- `np.zeros()`
- `np.ones()`
- `np.empty()`
- `np.arange()`
- `reshape()`
- `np.linspace()`

原视频对应的完整示例在[创建array配套内容](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-array)。

## 1. 使用 `np.array()` 创建数组


In [ ]:
import numpy as np

a = np.array([2, 23, 4])

print(a)


输出：

```text
[ 2 23  4]
```

NumPy 打印数组时，元素之间通常没有逗号。

普通列表：

```python
[2, 23, 4]
```

NumPy数组：

```text
[ 2 23  4]
```

查看类型：


In [ ]:
print(type(a))


输出：

```text
<class 'numpy.ndarray'>
```

---

## 2. 创建二维数组


In [ ]:
a = np.array([
    [2, 23, 4],
    [2, 32, 4]
])

print(a)


输出：

```text
[[ 2 23  4]
 [ 2 32  4]]
```

属性：


In [ ]:
print(a.ndim)
print(a.shape)
print(a.size)


输出：

```text
2
(2, 3)
6
```

---

## 3. 使用dtype指定数据类型


In [ ]:
a = np.array([2, 23, 4], dtype=np.int64)

print(a)
print(a.dtype)


输出：

```text
[ 2 23  4]
int64
```

指定32位整数：


In [ ]:
a = np.array([2, 23, 4], dtype=np.int32)

print(a.dtype)


输出：

```text
int32
```

指定64位浮点数：


In [ ]:
a = np.array([2, 23, 4], dtype=np.float64)

print(a)
print(a.dtype)


输出：

```text
[ 2. 23.  4.]
float64
```

指定32位浮点数：


In [ ]:
a = np.array([2, 23, 4], dtype=np.float32)

print(a.dtype)


输出：

```text
float32
```

大致理解：

| 类型 | 含义 |
|---|---|
| `int32` | 32位整数 |
| `int64` | 64位整数 |
| `float32` | 32位小数 |
| `float64` | 64位小数 |

位数越高，通常能表示的范围或精度越高，同时一般也会占用更多内存。

---

## 4. 创建全0数组：`np.zeros()`


In [ ]:
a = np.zeros((3, 4))

print(a)


输出：

```text
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
```

这里：

```python
(3, 4)
```

表示3行4列。

默认类型一般是：


In [ ]:
print(a.dtype)


输出：

```text
float64
```

如果想创建整数0：


In [ ]:
a = np.zeros((3, 4), dtype=int)

print(a)


输出：

```text
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
```

---

## 5. 创建全1数组：`np.ones()`


In [ ]:
a = np.ones((2, 3), dtype=int)

print(a)


输出：

```text
[[1 1 1]
 [1 1 1]]
```

视频中的旧代码可能写：

```python
dtype=np.int
```

现在不要照抄 `np.int`，应改成：

```python
dtype=int
```

或者明确写：

```python
dtype=np.int64
```

---

## 6. 创建未初始化数组：`np.empty()`


In [ ]:
a = np.empty((2, 3))

print(a)


可能输出：

```text
[[0.00000000e+000 0.00000000e+000 6.93831257e-310]
 [6.93831257e-310 2.12199579e-314 0.00000000e+000]]
```

你的结果很可能完全不同。

`empty` 不是“创建空数组”，也不保证里面是0。它的意思是：

> 只申请一块内存空间，不负责把里面初始化成确定的值。

这些值可能是内存中之前残留的内容。

因此：

```python
np.empty((2, 3))
```

适合后面马上覆盖全部元素的情况。

如果需要确定的0，请使用：

```python
np.zeros((2, 3))
```

---

## 7. 使用 `np.arange()`

注意正确拼写是：

```text
arange
```

可以理解成：

```text
array range
```

示例：


In [ ]:
a = np.arange(10, 20, 2)

print(a)


输出：

```text
[10 12 14 16 18]
```

参数分别是：

```python
np.arange(开始值, 结束值, 步长)
```

和 `range()` 一样，包含开始值，不包含结束值：

```text
10：保留
12：保留
14：保留
16：保留
18：保留
20：到达结束值，不保留
```

NumPy官方也将其定义为半开区间 `[start, stop)`。[NumPy arange文档](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

更多例子：


In [ ]:
print(np.arange(5))
print(np.arange(2, 6))
print(np.arange(1, 10, 3))


输出：

```text
[0 1 2 3 4]
[2 3 4 5]
[1 4 7]
```

---

## 8. 使用 `reshape()` 改变形状


In [ ]:
a = np.arange(12)

print(a)


输出：

```text
[ 0  1  2  3  4  5  6  7  8  9 10 11]
```

这是一个长度为12的一维数组。

变成3行4列：


In [ ]:
b = a.reshape((3, 4))

print(b)


输出：

```text
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

元素数量必须相等：

```text
原来：12个元素
现在：3 × 4 = 12个元素
```

下面会报错：

```python
a.reshape((3, 5))
```

因为：

```text
3 × 5 = 15
```

但原数组只有12个元素。

报错类似：

```text
ValueError: cannot reshape array of size 12 into shape (3,5)
```

可以让 NumPy 自动推断一个维度：


In [ ]:
b = a.reshape((3, -1))

print(b.shape)


输出：

```text
(3, 4)
```

`-1` 表示：

> 这一维请根据元素总数自动计算。

---

## 9. 使用 `np.linspace()`


In [ ]:
a = np.linspace(0, 10, 5)

print(a)


输出：

```text
[ 0.   2.5  5.   7.5 10. ]
```

参数意思：

```python
np.linspace(开始值, 结束值, 数量)
```

这里不是步长5，而是：

> 从0到10，一共生成5个等间隔数字。

`linspace` 默认包含结束值。

对比：


In [ ]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 10, 5))


输出：

```text
[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
```

区别：

| 方法 | 第三个参数 | 是否通常包含结束值 |
|---|---|---|
| `arange` | 步长 | 不包含 |
| `linspace` | 要生成的数量 | 包含 |

---
