# 第5个视频：NumPy基础运算

> 原视频 P5：2.3 numpy 的基础运算｜时长：13分27秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

本集是前五集中最重要的一集，核心是：

- 对应位置加减乘除
- 乘方
- 数学函数
- 布尔判断
- 矩阵乘法
- 求和、最大值、最小值
- `axis` 的含义

原视频示例可对应[作者的基础运算内容](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-math1)。

## 1. 准备两个数组


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.arange(4)

print(a)
print(b)


输出：

```text
[10 20 30 40]
[0 1 2 3]
```

它们的形状都是：


In [ ]:
print(a.shape)
print(b.shape)


输出：

```text
(4,)
(4,)
```

---

## 2. 对应位置相减


In [ ]:
c = a - b

print(c)


输出：

```text
[10 19 28 37]
```

计算过程：

```text
10 - 0 = 10
20 - 1 = 19
30 - 2 = 28
40 - 3 = 37
```

---

## 3. 对应位置相加


In [ ]:
c = a + b

print(c)


输出：

```text
[10 21 32 43]
```

计算过程：

```text
10 + 0 = 10
20 + 1 = 21
30 + 2 = 32
40 + 3 = 43
```

---

## 4. 对应位置相乘


In [ ]:
c = a * b

print(c)


输出：

```text
[  0  20  60 120]
```

计算过程：

```text
10 × 0 = 0
20 × 1 = 20
30 × 2 = 60
40 × 3 = 120
```

注意：

> NumPy数组中的 `*` 默认是对应位置相乘，不是线性代数中的矩阵乘法。

---

## 5. 对应位置相除


In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print(a / b)


输出：

```text
[5. 5. 6. 5.]
```

即使两个数组都是整数，普通除法 `/` 通常也会得到浮点数。

---

## 6. 乘方运算


In [ ]:
b = np.arange(4)

print(b)
print(b ** 2)


输出：

```text
[0 1 2 3]
[0 1 4 9]
```

计算过程：

```text
0² = 0
1² = 1
2² = 4
3² = 9
```

立方：


In [ ]:
print(b ** 3)


输出：

```text
[ 0  1  8 27]
```

---

## 7. 数组和一个数字运算


In [ ]:
a = np.array([1, 2, 3, 4])

print(a + 10)
print(a * 10)


输出：

```text
[11 12 13 14]
[10 20 30 40]
```

NumPy自动把数字10作用到每一个元素上：

```text
a + 10
↓
[1+10, 2+10, 3+10, 4+10]
```

这是最简单的广播。

---

## 8. 数学函数


In [ ]:
b = np.array([0, 1, 2, 3])

print(np.sin(b))


输出近似为：

```text
[0.         0.84147098 0.90929743 0.14112001]
```

注意：

```python
np.sin()
```

使用的是弧度，不是角度。

如果想计算30度的正弦值：


In [ ]:
angle = 30

result = np.sin(np.deg2rad(angle))

print(result)


输出约为：

```text
0.49999999999999994
```

理论值就是：

```text
0.5
```

出现很长的小数是浮点数精度现象。

可以四舍五入：


In [ ]:
print(np.round(result, 2))


输出：

```text
0.5
```

---

## 9. 数组进行条件判断


In [ ]:
b = np.arange(4)

print(b)
print(b < 3)


输出：

```text
[0 1 2 3]
[ True  True  True False]
```

NumPy分别判断每一个元素：

```text
0 < 3 → True
1 < 3 → True
2 < 3 → True
3 < 3 → False
```

得到的是布尔数组。

查看类型：


In [ ]:
result = b < 3

print(result.dtype)


输出：

```text
bool
```

---

## 10. 使用布尔数组筛选数据


In [ ]:
b = np.array([0, 1, 2, 3, 4, 5])

condition = b < 3

print(condition)
print(b[condition])


输出：

```text
[ True  True  True False False False]
[0 1 2]
```

通常直接写：


In [ ]:
print(b[b < 3])


输出：

```text
[0 1 2]
```

执行过程：

```text
b       = [0,    1,    2,     3,     4,     5]
b < 3   = [True, True, True, False, False, False]
保留结果 = [0,    1,    2]
```

这叫布尔索引，后面处理数据时非常重要。

---

## 11. `*`和矩阵乘法的区别

准备两个二维数组：


In [ ]:
a = np.array([
    [1, 1],
    [0, 1]
])

b = np.array([
    [0, 1],
    [2, 3]
])

print(a)
print(b)


输出：

```text
[[1 1]
 [0 1]]

[[0 1]
 [2 3]]
```

### 对应位置相乘


In [ ]:
print(a * b)


输出：

```text
[[0 1]
 [0 3]]
```

计算方式：

```text
1×0  1×1
0×2  1×3
```

所以得到：

```text
0 1
0 3
```

---

### 标准矩阵乘法

原视频使用：


In [ ]:
print(np.dot(a, b))


输出：

```text
[[2 4]
 [2 3]]
```

也可以写：


In [ ]:
print(a.dot(b))


输出相同：

```text
[[2 4]
 [2 3]]
```

现代代码中二维矩阵乘法还常写：


In [ ]:
print(a @ b)


输出：

```text
[[2 4]
 [2 3]]
```

第一行第一列的计算：

```text
1×0 + 1×2 = 2
```

第一行第二列：

```text
1×1 + 1×3 = 4
```

第二行第一列：

```text
0×0 + 1×2 = 2
```

第二行第二列：

```text
0×1 + 1×3 = 3
```

所以结果为：

```text
[[2 4]
 [2 3]]
```

务必记住：

```text
a * b       → 对应位置相乘
a @ b       → 矩阵乘法
np.dot(a,b) → 二维情况下也是矩阵乘法
```

---

## 12. 求和、最大值和最小值

为了让输出固定，先不用随机数：


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(a)


输出：

```text
[[1 2 3 4]
 [5 6 7 8]]
```

全部元素求和：


In [ ]:
print(np.sum(a))


输出：

```text
36
```

计算：

```text
1+2+3+4+5+6+7+8 = 36
```

最小值：


In [ ]:
print(np.min(a))


输出：

```text
1
```

最大值：


In [ ]:
print(np.max(a))


输出：

```text
8
```

也可以写成数组自己的方法：


In [ ]:
print(a.sum())
print(a.min())
print(a.max())


输出：

```text
36
1
8
```

---

## 13. `axis=0`是什么意思

原数组：

```text
[[1 2 3 4]
 [5 6 7 8]]
```

执行：


In [ ]:
print(np.sum(a, axis=0))


输出：

```text
[ 6  8 10 12]
```

`axis=0` 会把上下方向的行压缩掉，得到每一列的结果：

```text
第1列：1 + 5 = 6
第2列：2 + 6 = 8
第3列：3 + 7 = 10
第4列：4 + 8 = 12
```

所以：

```text
axis=0 → 按列统计
```

结果有4个数，因为原来有4列。

---

## 14. `axis=1`是什么意思


In [ ]:
print(np.sum(a, axis=1))


输出：

```text
[10 26]
```

分别计算每一行：

```text
第1行：1 + 2 + 3 + 4 = 10
第2行：5 + 6 + 7 + 8 = 26
```

所以：

```text
axis=1 → 按行统计
```

结果有2个数，因为原来有2行。

---

## 15. axis完整示例


In [ ]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print("所有元素求和：", np.sum(a))
print("每列求和：", np.sum(a, axis=0))
print("每行求和：", np.sum(a, axis=1))

print("每列最小值：", np.min(a, axis=0))
print("每行最大值：", np.max(a, axis=1))


输出：

```text
所有元素求和： 36
每列求和： [ 6  8 10 12]
每行求和： [10 26]
每列最小值： [1 2 3 4]
每行最大值： [4 8]
```

最简单的记忆方式：

```text
axis=0：上下计算，得到每列结果
axis=1：左右计算，得到每行结果
```

---

# 前五集知识总表

| 知识 | 作用 | 示例 |
|---|---|---|
| `np.array()` | 创建NumPy数组 | `np.array([1,2,3])` |
| `ndim` | 查看维度 | `a.ndim` |
| `shape` | 查看形状 | `a.shape` |
| `size` | 查看元素总数 | `a.size` |
| `dtype` | 查看数据类型 | `a.dtype` |
| `np.zeros()` | 创建全0数组 | `np.zeros((2,3))` |
| `np.ones()` | 创建全1数组 | `np.ones((2,3))` |
| `np.empty()` | 创建未初始化数组 | `np.empty((2,3))` |
| `np.arange()` | 根据步长生成数组 | `np.arange(0,10,2)` |
| `np.linspace()` | 根据数量等分区间 | `np.linspace(0,10,5)` |
| `reshape()` | 改变数组形状 | `a.reshape((3,4))` |
| `a+b` | 对应位置相加 | `[1,2]+[3,4]` |
| `a*b` | 对应位置相乘 | 元素乘法 |
| `a@b` | 矩阵乘法 | 行乘列 |
| `a<3` | 对每个元素判断 | 返回布尔数组 |
| `a[a<3]` | 根据条件筛选 | 布尔索引 |
| `np.sum()` | 求和 | `np.sum(a)` |
| `axis=0` | 按列统计 | 上下计算 |
| `axis=1` | 按行统计 | 左右计算 |

前五集最关键的三句话是：

```text
1. NumPy数组通常保存统一类型的数据，可以进行向量化计算。
2. shape看数组结构，size看元素总量，ndim看维度数量。
3. a*b是对应位置相乘，a@b才是标准矩阵乘法。
```
