# 第6集：NumPy基础运算2

> 原视频 P6：2.4 numpy 的基础运算 2｜时长：13分58秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

这一集学习更多数组计算方法：

```python
argmin()
argmax()
mean()
average()
median()
cumsum()
diff()
nonzero()
sort()
transpose()
clip()
```

原视频配套内容：[NumPy基础运算2](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-math2)

## 1. 准备数组


In [ ]:
import numpy as np

A = np.arange(2, 14).reshape((3, 4))

print(A)


输出：

```text
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
```

数组属性：


In [ ]:
print(A.shape)
print(A.size)


输出：

```text
(3, 4)
12
```

这是3行4列，一共12个元素。

---

## 2. `argmin()`：最小值的位置


In [ ]:
print(np.argmin(A))


输出：

```text
0
```

数组中的最小值是：

```text
2
```

如果把二维数组临时看成一维：

```text
索引： 0  1  2  3  4  5  6  7  8  9  10 11
数值： 2  3  4  5  6  7  8  9  10 11 12 13
```

最小值 `2` 的索引是 `0`，所以：

```python
np.argmin(A)
```

返回：

```text
0
```

注意：

```python
np.min(A)
```

返回最小值。

```python
np.argmin(A)
```

返回最小值所在的位置。

对比：


In [ ]:
print(np.min(A))
print(np.argmin(A))


输出：

```text
2
0
```

---

## 3. `argmax()`：最大值的位置


In [ ]:
print(np.argmax(A))


输出：

```text
11
```

最大值是 `13`，它在展开后的数组中位于索引 `11`。


In [ ]:
print(np.max(A))
print(np.argmax(A))


输出：

```text
13
11
```

---

## 4. 把一维索引转换成行列坐标

`argmax()` 默认返回展开后的索引。如果想知道它在第几行、第几列：


In [ ]:
index = np.argmax(A)
position = np.unravel_index(index, A.shape)

print(index)
print(position)


输出：

```text
11
(2, 3)
```

表示：

```text
行索引 = 2
列索引 = 3
```

也就是第三行、第四列：


In [ ]:
print(A[2, 3])


输出：

```text
13
```

---

## 5. 按行或按列找最大值的位置


In [ ]:
print(np.argmax(A, axis=0))


输出：

```text
[2 2 2 2]
```

`axis=0` 是按列计算：

```text
第0列：[2, 6, 10]  最大值位于行索引2
第1列：[3, 7, 11]  最大值位于行索引2
第2列：[4, 8, 12]  最大值位于行索引2
第3列：[5, 9, 13]  最大值位于行索引2
```

按行：


In [ ]:
print(np.argmax(A, axis=1))


输出：

```text
[3 3 3]
```

每行最大值都在列索引 `3`。

---

## 6. `mean()`：平均值


In [ ]:
print(np.mean(A))


输出：

```text
7.5
```

计算过程：

```text
所有元素之和 = 90
元素数量 = 12

90 ÷ 12 = 7.5
```

也可以写：


In [ ]:
print(A.mean())


输出：

```text
7.5
```

按列求平均值：


In [ ]:
print(np.mean(A, axis=0))


输出：

```text
[6. 7. 8. 9.]
```

计算：

```text
第0列：(2 + 6 + 10) ÷ 3 = 6
第1列：(3 + 7 + 11) ÷ 3 = 7
第2列：(4 + 8 + 12) ÷ 3 = 8
第3列：(5 + 9 + 13) ÷ 3 = 9
```

按行求平均值：


In [ ]:
print(np.mean(A, axis=1))


输出：

```text
[ 3.5  7.5 11.5]
```

---

## 7. `average()`：平均值


In [ ]:
print(np.average(A))


输出：

```text
7.5
```

在没有指定权重时：

```python
np.mean(A)
np.average(A)
```

结果通常相同。

但是 `average()` 可以计算加权平均值：


In [ ]:
scores = np.array([80, 90, 100])
weights = np.array([1, 2, 3])

result = np.average(scores, weights=weights)

print(result)


输出：

```text
93.33333333333333
```

计算过程：

```text
80×1 + 90×2 + 100×3
────────────────────
       1+2+3

= 560 ÷ 6
= 93.333...
```

所以：

```text
mean    → 普通平均值
average → 可以传入权重
```

---

## 8. `median()`：中位数


In [ ]:
print(np.median(A))


输出：

```text
7.5
```

数组展开后：

```text
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
```

一共有12个数字，中间两个是：

```text
7和8
```

所以：

```text
(7 + 8) ÷ 2 = 7.5
```

注意原配套网页中出现了：

```python
A.median()
```

现代 NumPy 的普通 `ndarray` 没有这个方法，会报错：

```text
AttributeError: 'numpy.ndarray' object has no attribute 'median'
```

正确写法是：

```python
np.median(A)
```

---

## 9. `cumsum()`：累加


In [ ]:
print(np.cumsum(A))


输出：

```text
[ 2  5  9 14 20 27 35 44 54 65 77 90]
```

它会先按照从左到右、从上到下展开，然后不断累加：

```text
第1个：2
第2个：2 + 3 = 5
第3个：2 + 3 + 4 = 9
第4个：2 + 3 + 4 + 5 = 14
第5个：2 + 3 + 4 + 5 + 6 = 20
……
```

按行累加：


In [ ]:
print(np.cumsum(A, axis=1))


输出：

```text
[[ 2  5  9 14]
 [ 6 13 21 30]
 [10 21 33 46]]
```

第一行：

```text
2
2+3=5
2+3+4=9
2+3+4+5=14
```

按列累加：


In [ ]:
print(np.cumsum(A, axis=0))


输出：

```text
[[ 2  3  4  5]
 [ 8 10 12 14]
 [18 21 24 27]]
```

例如第一列：

```text
2
2+6=8
2+6+10=18
```

---

## 10. `diff()`：相邻元素之差


In [ ]:
print(np.diff(A))


输出：

```text
[[1 1 1]
 [1 1 1]
 [1 1 1]]
```

默认沿最后一个轴，也就是逐行计算：

```text
3 - 2 = 1
4 - 3 = 1
5 - 4 = 1
```

原来每行4个数，相邻差值只有3个，所以形状从：

```text
(3, 4)
```

变成：

```text
(3, 3)
```

查看：


In [ ]:
result = np.diff(A)

print(result.shape)


输出：

```text
(3, 3)
```

沿着上下方向计算：


In [ ]:
print(np.diff(A, axis=0))


输出：

```text
[[4 4 4 4]
 [4 4 4 4]]
```

计算：

```text
第二行 - 第一行
第三行 - 第二行
```

---

## 11. `nonzero()`：找出非零元素的位置

重新准备一个包含0的数组：


In [ ]:
B = np.array([
    [0, 2, 0],
    [3, 0, 4]
])

result = np.nonzero(B)

print(result)


输出：

```text
(array([0, 1, 1]), array([1, 0, 2]))
```

这个结果分成两个数组：

```text
第一个数组：非零元素的行索引
第二个数组：非零元素的列索引
```

组合起来：

```text
(0, 1) → 数值2
(1, 0) → 数值3
(1, 2) → 数值4
```

可以这样查看：


In [ ]:
rows, columns = np.nonzero(B)

for row, column in zip(rows, columns):
    print(f"位置：({row}, {column})，数值：{B[row, column]}")


输出：

```text
位置：(0, 1)，数值：2
位置：(1, 0)，数值：3
位置：(1, 2)，数值：4
```

---

## 12. `sort()`：排序


In [ ]:
A = np.arange(14, 2, -1).reshape((3, 4))

print(A)


输出：

```text
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
```

排序：


In [ ]:
result = np.sort(A)

print(result)


输出：

```text
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
```

默认按照每一行排序。

重要区别：


In [ ]:
result = np.sort(A)


返回一个排序后的新数组，原来的 `A` 不变。

```python
A.sort()
```

直接修改原来的 `A`，返回值是 `None`。

---

## 13. 转置：`transpose()`和`.T`


In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A.T)


输出：

```text
[[1 4]
 [2 5]
 [3 6]]
```

原来的形状：

```text
2行3列
```

转置以后：

```text
3行2列
```

两种写法：

```python
np.transpose(A)
A.T
```

结果相同。


In [ ]:
print(np.transpose(A))
print(A.T)


输出：

```text
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]
```

---

## 14. `clip()`：限制数值范围


In [ ]:
A = np.array([
    [14, 13, 12, 11],
    [10,  9,  8,  7],
    [ 6,  5,  4,  3]
])

print(np.clip(A, 5, 9))


输出：

```text
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
```

规则是：

```text
小于5 → 改成5
5～9  → 保持不变
大于9 → 改成9
```

例如：

```text
14 → 9
10 → 9
8  → 8
7  → 7
4  → 5
3  → 5
```

`clip` 经常用来限制：

- 像素值范围
- 分数范围
- 概率范围
- 异常数据

---
