# 第7集：NumPy索引

> 原视频 P7：2.5 numpy 的索引｜时长：9分29秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

这一集学习如何通过索引、切片和循环取出数组中的元素。[原视频配套索引内容](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-indexing)

## 1. 一维数组索引


In [ ]:
import numpy as np

A = np.arange(3, 15)

print(A)


输出：

```text
[ 3  4  5  6  7  8  9 10 11 12 13 14]
```

取索引3：


In [ ]:
print(A[3])


输出：

```text
6
```

因为索引从0开始：

```text
索引：0  1  2  3  4
数值：3  4  5  6  7
```

---

## 2. 负数索引


In [ ]:
print(A[-1])
print(A[-2])


输出：

```text
14
13
```

- `-1`：最后一个
- `-2`：倒数第二个

---

## 3. 一维数组切片


In [ ]:
print(A[2:6])


输出：

```text
[5 6 7 8]
```

规则：

```text
包含开始索引2
不包含结束索引6
```

带步长：


In [ ]:
print(A[1:9:2])


输出：

```text
[ 4  6  8 10]
```

完整格式：

```python
数组[开始:结束:步长]
```

---

## 4. 二维数组索引


In [ ]:
A = np.arange(3, 15).reshape((3, 4))

print(A)


输出：

```text
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
```

取出索引为2的行：


In [ ]:
print(A[2])


输出：

```text
[11 12 13 14]
```

也就是第三行。

---

## 5. 取出一个具体元素


In [ ]:
print(A[1][1])


输出：

```text
8
```

执行过程：

```python
A[1]
```

先得到第二行：

```text
[7 8 9 10]
```

然后：

```python
A[1][1]
```

从这行里取索引1，得到：

```text
8
```

NumPy更推荐直接写：


In [ ]:
print(A[1, 1])


输出：

```text
8
```

格式：

```python
A[行索引, 列索引]
```

---

## 6. 取出一整行


In [ ]:
print(A[1, :])


输出：

```text
[ 7  8  9 10]
```

这里：

```text
行索引1 → 第二行
:       → 所有列
```

也可以简写：

```python
A[1]
```

---

## 7. 取出一整列


In [ ]:
print(A[:, 1])


输出：

```text
[ 4  8 12]
```

这里：

```text
:       → 所有行
列索引1 → 第二列
```

结构：

```text
4
8
12
```

---

## 8. 同时切片行和列


In [ ]:
print(A[0:2, 1:3])


输出：

```text
[[4 5]
 [8 9]]
```

先取行：

```text
0:2 → 第0行和第1行
```

再取列：

```text
1:3 → 第1列和第2列
```

对应原数组：

```text
      列0 列1 列2 列3
行0    3  [4   5]  6
行1    7  [8   9] 10
行2   11  12  13  14
```

---

## 9. 遍历每一行


In [ ]:
for row in A:
    print(row)


输出：

```text
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
```

直接遍历二维 NumPy 数组时，每次得到一行。

---

## 10. 遍历每一列


In [ ]:
for column in A.T:
    print(column)


输出：

```text
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
```

原数组：

```text
3   4   5   6
7   8   9  10
11 12  13  14
```

转置以后：

```text
3  7 11
4  8 12
5  9 13
6 10 14
```

再逐行遍历转置数组，就相当于遍历原来的每一列。

---

## 11. `flatten()`：展开数组


In [ ]:
flat_array = A.flatten()

print(flat_array)
print(flat_array.shape)


输出：

```text
[ 3  4  5  6  7  8  9 10 11 12 13 14]
(12,)
```

原来是：

```text
(3, 4)
```

展开以后：

```text
(12,)
```

`flatten()` 会产生一个独立的新数组。

---

## 12. `.flat`：逐个遍历所有元素


In [ ]:
for item in A.flat:
    print(item, end=" ")


输出：

```text
3 4 5 6 7 8 9 10 11 12 13 14
```

区别：

```text
A.flatten() → 返回一个展开后的数组
A.flat      → 返回用于逐个访问元素的迭代器
```

---
