# 第8集：NumPy数组合并

> 原视频 P8：2.6 numpy 的 array 合并｜时长：11分13秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

本集学习：

```python
vstack()
hstack()
newaxis
concatenate()
```

原视频配套内容：[NumPy array合并](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-concat)

## 1. 准备两个一维数组


In [ ]:
import numpy as np

A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

print(A.shape)
print(B.shape)


输出：

```text
(3,)
(3,)
```

它们都是一维数组。

---

## 2. `vstack()`：上下合并

`v` 是 vertical，表示垂直方向。


In [ ]:
C = np.vstack((A, B))

print(C)
print(C.shape)


输出：

```text
[[1 1 1]
 [2 2 2]]
(2, 3)
```

合并过程：

```text
A：[1 1 1]
B：[2 2 2]

上下叠放：

[1 1 1]
[2 2 2]
```

注意参数外面是一个元组：

```python
np.vstack((A, B))
```

---

## 3. `hstack()`：左右合并

`h` 是 horizontal，表示水平方向。


In [ ]:
D = np.hstack((A, B))

print(D)
print(D.shape)


输出：

```text
[1 1 1 2 2 2]
(6,)
```

合并过程：

```text
[1 1 1] + [2 2 2]
            ↓
[1 1 1 2 2 2]
```

结果仍然是一维数组。

---

## 4. 为什么一维数组转置没有变化


In [ ]:
print(A)
print(A.T)

print(A.shape)
print(A.T.shape)


输出：

```text
[1 1 1]
[1 1 1]
(3,)
(3,)
```

一维数组只有一个轴，没有明确的“行”和“列”，所以 `.T` 不会把它变成列数组。

如果希望得到：

```text
[[1]
 [1]
 [1]]
```

需要主动增加维度。

---

## 5. `np.newaxis`：增加一个维度

### 变成一行三列


In [ ]:
row = A[np.newaxis, :]

print(row)
print(row.shape)


输出：

```text
[[1 1 1]]
(1, 3)
```

解释：

```text
np.newaxis → 在这里增加一个新维度
:          → 原来的所有元素
```

---

### 变成三行一列


In [ ]:
column = A[:, np.newaxis]

print(column)
print(column.shape)


输出：

```text
[[1]
 [1]
 [1]]
(3, 1)
```

可以这样记：

```python
A[np.newaxis, :]
```

在前面增加维度：

```text
(3,) → (1, 3)
```

```python
A[:, np.newaxis]
```

在后面增加维度：

```text
(3,) → (3, 1)
```

现代代码也可以使用 `None`：

```python
A[None, :]
A[:, None]
```

和 `np.newaxis` 效果相同。

---

## 6. 二维列数组的合并


In [ ]:
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]

print(A)
print(B)


输出：

```text
[[1]
 [1]
 [1]]

[[2]
 [2]
 [2]]
```

它们的形状都是：

```text
(3, 1)
```

左右合并：


In [ ]:
D = np.hstack((A, B))

print(D)
print(D.shape)


输出：

```text
[[1 2]
 [1 2]
 [1 2]]
(3, 2)
```

也就是：

```text
A作为第一列
B作为第二列
```

---

## 7. `concatenate()`：按照指定轴合并

准备：


In [ ]:
A = np.array([1, 1, 1])[:, np.newaxis]
B = np.array([2, 2, 2])[:, np.newaxis]


### `axis=0`


In [ ]:
C = np.concatenate((A, B, B, A), axis=0)

print(C)
print(C.shape)


输出：

```text
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
(12, 1)
```

`axis=0` 表示沿第0轴合并，行数增加：

```text
(3,1) + (3,1) + (3,1) + (3,1)
                    ↓
                  (12,1)
```

---

### `axis=1`


In [ ]:
D = np.concatenate((A, B, B, A), axis=1)

print(D)
print(D.shape)


输出：

```text
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]
(3, 4)
```

`axis=1` 表示列数增加：

```text
(3,1) + (3,1) + (3,1) + (3,1)
                    ↓
                   (3,4)
```

---

## 8. 合并时的形状要求

沿 `axis=0` 合并时，列数必须一致：


In [ ]:
A = np.ones((2, 3))
B = np.zeros((4, 3))

C = np.concatenate((A, B), axis=0)

print(C.shape)


输出：

```text
(6, 3)
```

因为两个数组都有3列。

沿 `axis=1` 合并时，行数必须一致：


In [2]:
import numpy as np
A = np.ones((2, 3))
B = np.zeros((2, 4))

C = np.concatenate((A, B), axis=1)

print(C.shape)
print(C)


(2, 7)
[[1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]]


输出：

```text
(2, 7)
```

因为两个数组都有2行。

---
