# 第9集：NumPy数组分割

> 原视频 P9：2.7 numpy 的 array 分割｜时长：6分57秒

本笔记严格依照原聊天记录中的讲解顺序整理。每个知识点先解释含义，再给出代码和记录中的预期输出；标为旧写法或故意报错的片段只用于阅读，不作为可执行单元。

合并是把多个数组变成一个；分割是把一个数组拆成多个。

本集学习：

```python
split()
array_split()
vsplit()
hsplit()
```

原视频配套内容：[NumPy array分割](https://mofanpy.com/tutorials/data-manipulation/np-pd/np-split)

## 1. 准备数组


In [ ]:
import numpy as np

A = np.arange(12).reshape((3, 4))

print(A)


输出：

```text
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

形状：

```text
3行4列
```

---

## 2. 沿 `axis=1` 分成两份


In [ ]:
result = np.split(A, 2, axis=1)

print(result)


输出：

```text
[array([[0, 1],
       [4, 5],
       [8, 9]]),
 array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
```

为了看得更清楚：


In [ ]:
for item in result:
    print(item)
    print("形状：", item.shape)


输出：

```text
[[0 1]
 [4 5]
 [8 9]]
形状： (3, 2)

[[ 2  3]
 [ 6  7]
 [10 11]]
形状： (3, 2)
```

原来4列，分成2份，每份2列：

```text
[0 1 | 2 3]
[4 5 | 6 7]
[8 9 |10 11]
```

---

## 3. 沿 `axis=0` 分成三份


In [ ]:
result = np.split(A, 3, axis=0)

for item in result:
    print(item)


输出：

```text
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
```

原来3行，分成3份，每份1行。

---

## 4. “横向分割”和“纵向分割”容易混淆

视频中会使用横向、纵向这样的说法，但不同人可能理解不同：

```text
按横线切，还是切成横向的小块？
按竖线切，还是切成纵向的小块？
```

所以最好直接看 `axis`：

```text
axis=0 → 拆分行
axis=1 → 拆分列
```

对于二维数组：

```python
np.split(A, 3, axis=0)
```

拆成上、中、下几部分。

```python
np.split(A, 2, axis=1)
```

拆成左、右几部分。

---

## 5. 不能整除时会报错

数组有4列：

```python
A.shape
```

是：

```text
(3, 4)
```

如果把4列平均分成3份：

```python
np.split(A, 3, axis=1)
```

会报错：

```text
ValueError: array split does not result in an equal division
```

因为：

```text
4 ÷ 3
```

不能平均分割。

`np.split()` 要求每份大小相等。

---

## 6. `array_split()`：允许不等量分割


In [ ]:
result = np.array_split(A, 3, axis=1)

for item in result:
    print(item)
    print("形状：", item.shape)


输出：

```text
[[0 1]
 [4 5]
 [8 9]]
形状： (3, 2)

[[ 2]
 [ 6]
 [10]]
形状： (3, 1)

[[ 3]
 [ 7]
 [11]]
形状： (3, 1)
```

4列分成3份，NumPy分配成：

```text
2列、1列、1列
```

区别：

```text
split       → 必须平均分
array_split → 可以不平均
```

---

## 7. `vsplit()`：上下分割


In [ ]:
result = np.vsplit(A, 3)

for item in result:
    print(item)


输出：

```text
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
```

它相当于：

```python
np.split(A, 3, axis=0)
```

`vsplit` 可以理解为 vertical split，沿上下方向拆成多块。

---

## 8. `hsplit()`：左右分割


In [ ]:
result = np.hsplit(A, 2)

for item in result:
    print(item)


输出：

```text
[[0 1]
 [4 5]
 [8 9]]

[[ 2  3]
 [ 6  7]
 [10 11]]
```

它相当于：

```python
np.split(A, 2, axis=1)
```

总结：

```text
vsplit(A, n) → 拆分行，相当于axis=0
hsplit(A, n) → 拆分列，相当于axis=1
```

---
